fn main() {
    cc::Build::new()
        .files([
            "cubiomes/generator.c",
            "cubiomes/biomenoise.c",
            "cubiomes/biomes.c",
            "cubiomes/layers.c",
            "cubiomes/noise.c",
            "cubiomes/util.c",
            "cubiomes/finders.c",
            "cubiomes/quadbase.c",
            "cubiomes_shim.c",
        ])
        .include("cubiomes")
        .flag_if_supported("-O3")           
        .flag_if_supported("-fwrapv")       
        .flag_if_supported("-march=native") 
        .flag_if_supported("-mtune=native") 
        .flag_if_supported("-funroll-loops")
        .flag_if_supported("-ffast-math")  
        .flag_if_supported("-fomit-frame-pointer") 
        .flag_if_supported("-fprefetch-loop-arrays")
        .flag_if_supported("/O2")
        .flag_if_supported("/Oi")          
        .flag_if_supported("/Ot")           
        .compile("cubiomes");

    println!("cargo:rerun-if-changed=cubiomes_shim.c");
    println!("cargo:rerun-if-changed=cubiomes/generator.c");
    println!("cargo:rerun-if-changed=cubiomes/generator.h");
}
